# Generated by Django 3.2.8 on 2022-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20220404_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Soccer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_contact', models.CharField(max_length=52)),
                ('customer_name', models.CharField(blank=True, max_length=52, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=52, null=True)),
                ('booking_type', models.CharField(choices=[('Hockey', 'hockey'), ('Soccer', 'Soccer'), ('Woodball', 'woodball')], max_length=52)),
                ('venue', models.CharField(max_length=152)),
                ('court_location', models.CharField(choices=[('Pitch 1', 'pitch_one'), ('Pitch 2', 'pitch_two'), ('Pitch 3', 'pitch_three')], max_length=52)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.CharField(max_length=102)),
                ('block_booking', models.BooleanField(default=False)),
                ('cost', models.IntegerField()),
                ('blocked_off', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Battallion_five',
        ),
        migrations.DeleteModel(
            name='Battallion_four',
        ),
        migrations.DeleteModel(
            name='Battallion_one',
        ),
        migrations.DeleteModel(
            name='Battallion_six',
        ),
        migrations.DeleteModel(
            name='Battallion_three',
        ),
        migrations.DeleteModel(
            name='Deleted_Employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_request_access',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_request_battalion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='battallion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lower_level_incharge',
        ),
        migrations.RemoveField(
            model_name='user',
            name='section',
        ),
        migrations.RemoveField(
            model_name='user',
            name='top_level_incharge',
        ),
    ]
