# Generated by Django 3.2.8 on 2022-06-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20220620_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Battallion_two',
        ),
        migrations.AlterModelOptions(
            name='booking_soccer',
            options={'verbose_name': 'Soccer Booking', 'verbose_name_plural': 'Soccer Bookings'},
        ),
    ]
