# Generated by Django 3.2.8 on 2022-06-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220620_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_soccer',
            name='booking_type',
            field=models.CharField(choices=[('Hockey', 'Hockey'), ('Soccer', 'Soccer'), ('Woodball', 'Woodball')], max_length=52),
        ),
        migrations.AlterField(
            model_name='booking_soccer',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking_soccer',
            name='court_location',
            field=models.CharField(choices=[('Pitch 1', 'Pitch 1'), ('Pitch 2', 'Pitch 2'), ('Pitch 3', 'Pitch 3')], max_length=52),
        ),
        migrations.AlterField(
            model_name='booking_soccer',
            name='start_date',
            field=models.DateField(),
        ),
    ]
