# Generated by Django 3.2.8 on 2022-06-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20220622_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_soccer',
            name='blocked_off',
            field=models.BooleanField(default=False),
        ),
    ]
