# Generated by Django 3.2.8 on 2022-06-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_booking_soccer_blocked_off'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking_Soccer',
            new_name='Booking',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
    ]
