# Generated by Django 3.2.8 on 2022-07-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20220622_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='verified_by',
            field=models.CharField(blank=True, max_length=102, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='blocked_off',
            field=models.BooleanField(default=False, help_text='Veried Booking?'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('Hockey', 'Hockey'), ('Soccer', 'Soccer'), ('Woodball', 'Woodball'), ('Basket Ball', 'Basket Ball')], max_length=52),
        ),
        migrations.AlterField(
            model_name='booking',
            name='court_location',
            field=models.CharField(choices=[('Pitch 1', 'Pitch 1'), ('Pitch 2', 'Pitch 2'), ('Pitch 3', 'Pitch 3'), ('Tusker Court', 'Tusker Court')], max_length=52),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(blank=True, max_length=102, null=True),
        ),
    ]
