# Generated by Django 3.2.8 on 2022-07-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220704_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Cancel Booking?'),
        ),
    ]
