# Generated by Django 3.2.8 on 2022-07-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_booking_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_contact', models.CharField(max_length=52)),
                ('customer_name', models.CharField(blank=True, max_length=52, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=52, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
