# Generated by Django 3.2.8 on 2022-07-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('Hockey', 'Hockey'), ('Soccer', 'Soccer'), ('Woodball', 'Woodball'), ('Basket Ball', 'Basket Ball'), ('Volley Ball', 'Volley Ball'), ('Net Ball', 'Net Ball')], max_length=52),
        ),
    ]
