# Generated by Django 3.2.8 on 2022-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='interval',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly')], max_length=52, null=True),
        ),
    ]
