# Generated by Django 3.2.8 on 2022-08-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_booking_send_verification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_data_record',
            field=models.DateField(blank=True, null=True),
        ),
    ]
