# Generated by Django 3.2.8 on 2022-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20220803_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='start_data_record',
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date_record',
            field=models.DateField(blank=True, null=True),
        ),
    ]
