# Generated by Django 3.2.8 on 2022-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20220920_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='pactient',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
